name: Pull Request CI

on:
  pull_request:
    branches: 
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Trocar para branch específica
        run: git checkout main   # ou a branch de destino

      - name: Configurar JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Instalar dependências e compilar
        run: mvn clean compile

      - name: Rodar testes
        run: mvn test
